### ISSUE TITLE
"500 Internal Error"

### ISSUE THREAD

**Issue by caitlynrw** [arnolicious/jelly-clipper#129]
When selecting a clip, I can select the audio track, then the site hangs and container restarts a few times before reporting a 500 error.

![Image](https://github.com/user-attachments/assets/84eb22df-60d7-43e9-8c34-b8600596eb2b)

jelly-clipper `compose.yml`
```yml
services:
  jelly-clipper:
    image: ghcr.io/arnolicious/jelly-clipper:latest
    container_name: jelly-clipper
    ports:
      - 3000:3000
    volumes:
      # Path to the db directory, in which the sqlite db file will live
      - ./data/:/app/db
      # Path to the videos directory.
      # This will store all the clips permanently and the original files temporarily,
      # so it might get a lil big
      - ./clips:/app/assets/videos
    restart: unless-stopped
    environment:
      # Timezone to have the cleanup cron job working as expected
      - TZ=Australia/Adelaide
      - JELLY_CLIPPER_ORIGIN=http://192.168.0.107:3000
```

I've used this container before (`v0.3.0` I think) and it worked fine.

This is the log from the container: https://pastie.io/rjtfob
