### ISSUE TITLE
Svelte 404 on install

### ISSUE THREAD

**Issue by 0belous** [arnolicious/jelly-clipper#35]
Ubuntu 24.04.1 LTS x86_64 
Latest via docker
Accessing via domain + cloudflare tunnel

First install via docker
```yml
services:
  jelly-clipper:
    image: ghcr.io/arnolicious/jelly-clipper:latest
    container_name: jelly-clipper
    ports:
      - 3001:3000
    volumes:
      # Path to the db directory, in which the sqlite db file will live
      - /home/obelous/clipdb:/app/db
      # Path to the videos directory.
      # This will store all the clips permanently and the original files temporarily,
      # so it might get a lil big
      - /paul/clips:/app/assets/videos
    restart: unless-stopped
    environment:
      # Timezone to have the cleanup cron job working as expected
      - TZ=Europe/Belfast
      # Full URL with Protocol and Port, where the application will live
      - JELLY_CLIPPER_ORIGIN=https://clip.obelous.dev/
```

The error

```bash
obelous@ubuntu:~/clips$ sudo docker-compose up
[+] Running 1/0
 ✔ Container jelly-clipper  Created                                                                                                                                                                               0.0s
Attaching to jelly-clipper
jelly-clipper  | listening on port 3000
jelly-clipper  | Server error SvelteKitError: Not found: //
jelly-clipper  |     at resolve2 (file:///app/build/server/index.js:4311:18)
jelly-clipper  |     at resolve (file:///app/build/server/index.js:4144:34)
jelly-clipper  |     at Object.handle (file:///app/build/server/chunks/hooks.server-PqQgCy-V.js:17:26)
jelly-clipper  |     at respond (file:///app/build/server/index.js:4142:43) {
jelly-clipper  |   status: 404,
jelly-clipper  |   text: 'Not Found'
jelly-clipper  | } Not Found
jelly-clipper  | Server error SvelteKitError: Not found: //
jelly-clipper  |     at resolve2 (file:///app/build/server/index.js:4311:18)
jelly-clipper  |     at resolve (file:///app/build/server/index.js:4144:34)
jelly-clipper  |     at Object.handle (file:///app/build/server/chunks/hooks.server-PqQgCy-V.js:17:26)
jelly-clipper  |     at respond (file:///app/build/server/index.js:4142:43) {
jelly-clipper  |   status: 404,
jelly-clipper  |   text: 'Not Found'
jelly-clipper  | } Not Found
```

![Image](https://github.com/user-attachments/assets/54c9966e-2520-4bd9-8109-1ddff628f09b)

Checked specified folders exist
```bash
obelous@ubuntu:~/clipdb$ ls
jelly-clipper.db

obelous@ubuntu:/paul/clips$ ls
obelous@ubuntu:/paul/clips$
```

**Comment by 0belous** [comment]
Solved!
Use this correct docker compose
and make sure -JELLY_CLIPPER_ORIGIN is set correctly to the url you will be accessing it from which probably wont include a port number, remembering to double check http vs https

```yml
services:
  jelly-clipper:
    image: arnolicious/jelly-clipper:latest
    container_name: jelly-clipper
    ports:
      - 3001:3000
    volumes:
      - ./deploy/db:/app/db
      - ./deploy/videos:/app/assets/videos
    restart: unless-stopped
    environment:
      - JELLY_CLIPPER_ORIGIN=http://localhost:3001
      - TZ=Europe/Berlin
```
