### ISSUE TITLE
Cross-Site POST Form Submissions Are Forbidden

### ISSUE THREAD

**Issue by AKA-Mae** [arnolicious/jelly-clipper#49]
I set up Jelly-Clipper using the docker compose from the readme and am running into an error at the setup page
![Image](https://github.com/user-attachments/assets/047e348b-fba1-49c1-9c77-a320a13b9d82)
I have tried using the local IP with and without the port and the external address and all give the same "Cross-site POST form submissions are forbidden" error
This is the exact compose I used, with the origin url removed for privacy reasons, in case I somehow got something wrong:

```
services:
  jelly-clipper:
    image: ghcr.io/arnolicious/jelly-clipper:latest
    container_name: jelly-clipper
    ports:
      - 3000:3000
    volumes:
      # Path to the db directory, in which the sqlite db file will live
      - /home/mae/Drive/Jellyfin/ClipDB:/app/db
      # Path to the videos directory.
      # This will store all the clips permanently and the original files temporarily,
      # so it might get a lil big
      - /home/mae/Drive/Jellyfin/Media/Clips:/app/assets/videos
    restart: unless-stopped
    environment:
      # Timezone to have the cleanup cron job working as expected
      - TZ=America/Los_Angeles
      # Full URL with Protocol and Port, where the application will live
      - JELLY_CLIPPER_ORIGIN=
      # with a reverse proxy it could be something like:
      # - JELLY_CLIPPER_ORIGIN=https://clip.jellyfin.mydomain.test
```
